In [1]:
import numpy as np

n = int(input("number of rows:"))
m = int(input("number of colmuns:"))

#create a matrix with n rows and m columns
matrix = np.arange(n*m).reshape(n, m)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [2]:
# transpose the matrix
matrix= np.transpose(matrix)
matrix

array([[ 0,  7, 14, 21, 28],
       [ 1,  8, 15, 22, 29],
       [ 2,  9, 16, 23, 30],
       [ 3, 10, 17, 24, 31],
       [ 4, 11, 18, 25, 32],
       [ 5, 12, 19, 26, 33],
       [ 6, 13, 20, 27, 34]])

In [3]:
# reverse the matrix
matrix = matrix[:, ::-1]
matrix

array([[28, 21, 14,  7,  0],
       [29, 22, 15,  8,  1],
       [30, 23, 16,  9,  2],
       [31, 24, 17, 10,  3],
       [32, 25, 18, 11,  4],
       [33, 26, 19, 12,  5],
       [34, 27, 20, 13,  6]])